spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/crud_test
    username: root
    password: 1012
    driver-class-name: org.mariadb.jdbc.Driver

  thymeleaf:
    cache: false
    prefix: classpath:/templates/

  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
